[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/shape/page/*"
  to = "/shape/:splat"
  status = 301
  
[[redirects]]
  from = "/shape/*"
  to = "https://chromakode-reshape.netlify.app/:splat"
  status = 200
